# Description:
#   - Deepseek code review with GitHub Actions
# REF:
#   - https://github.com/marketplace/actions/checkout

name: Code Review@Dev
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

# fix: GraphQL: Resource not accessible by integration (addComment) error
permissions:
  pull-requests: write

jobs:
  setup-deepseek-review:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: Deepseek Code Review
        uses: hustcer/deepseek-review@develop
        with:
          deepseek-token: ${{ secrets.DEEPSEEK_TOKEN }}
