# Description:
#   - Deepseek code review with GitHub Actions
# REF:
#   - https://github.com/marketplace/actions/checkout

name: Code Review
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

# fix: GraphQL: Resource not accessible by integration (addComment) error
permissions:
  pull-requests: write

jobs:
  setup-deepseek-review:
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: Deepseek Code Review
        uses: hustcer/deepseek-review@develop
        with:
          max-length: 10000
          chat-token: ${{ secrets.CHAT_TOKEN }}
