name: Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *' # Run every morning at 7am UTC

permissions:
  contents: read

jobs:
  nutest-tests:
    name: Run Tests

    permissions:
      checks: write
      pull-requests: write

    strategy:
      fail-fast: true
      matrix:
        version: ["*", "nightly"] # Earliest supported, latest and nightly
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Nutest Repo
        uses: actions/checkout@v4
        with:
          ref: v1.0.1
          path: nutest
          repository: vyadh/nutest

      - name: Setup Nu
        uses: hustcer/setup-nu@v3
        with:
          version: ${{ matrix.version }}

      - name: Test Nutest
        shell: nu {0}
        run: |
          # const NU_LIB_DIRS = [ ${{ github.workspace }}/nutest/nutest ]
          # ls $NU_LIB_DIRS.0 | print
          pwd | print
          use ./nutest/nutest
          (
            nutest run-tests
              --fail
              --display terminal
              --report { type: junit, path: test-report.xml }
              --returns summary | to json | save --force test-summary.json
          )
