# Description: This workflow runs tests for hustcer/deepseek-review.
# REF:
#   - https://github.com/vyadh/nutest/blob/main/.github/workflows/tests.yaml

name: Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'   # Run every morning at 7am UTC

permissions:
  contents: read

jobs:
  nutest-tests:
    name: Run Tests

    permissions:
      checks: write

    strategy:
      fail-fast: true
      matrix:
        version: ['*', nightly]   # Earliest supported, latest and nightly
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Nutest Repo
        uses: actions/checkout@v4
        with:
          ref: v1.0.1
          path: nutest
          repository: vyadh/nutest
          sparse-checkout: nutest/

      - name: Setup Nu
        uses: hustcer/setup-nu@v3
        with:
          version: ${{ matrix.version }}

      - name: Test Deepseek Review
        shell: nu {0}
        run: |
          use ${{ github.workspace }}/nutest/nutest
          (
            nutest run-tests
              --fail
              --display terminal
              --report { type: junit, path: test-report.xml }
              --returns summary | to json | save --force test-summary.json
          )
